DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	message TEXT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	post_id INTEGER NOT NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
)